---

title: Sonos API
email: 1292510+svrooij@users.noreply.github.com

baseurl: "/sonos-api-docs"
url: "https://svrooij.io"
twitter_username: svrooij
github_username: svrooij
repository: svrooij/sonos-api-docs

# Build settings
markdown: kramdown
remote_theme: svrooij/just-the-docs@plausible
plugins:
  - jekyll-feed
  - jekyll-octicons
  - jemoji

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Repository":
    - "//github.com/svrooij/sonos-api-docs"
  "Sponsor @svrooij":
    - "//github.com/sponsors/svrooij/"

# Footer content appears at the bottom of every page's main content
footer_content: >
  Copyright &copy; 2022 Stephan van Rooij.
  Distributed under <a
  href=\"https://github.com/svrooij/sonos-api-docs/tree/main/LICENSE\">
  MIT license.</a>

toc:
  max_levels: 2

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Source on Github"
gh_edit_repository: "https://github.com/svrooij/sonos-api-docs"
gh_edit_branch: "main/docs" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" 

plausible_domain: "sonos.svrooij.io"
